# No bash, can still use once confident
# FROM node:alpine

FROM node:14

RUN mkdir -p /app/client
WORKDIR /app/client
RUN npm install -g create-react-app
COPY package*.json /app/client/

RUN npm install --silent

COPY . /app/client/

CMD ["npm", "start"]