version: '3.8'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: server
    container_name: server
    command: npm run start
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    env_file: ./server/.env
    environment:
      - NODE_ENV=development
    networks:
      - app-network


  mongo:
    image: mongo:latest
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network


  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: client
    container_name: client
    command: npm run start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    stdin_open: true
    depends_on:
      - server
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
    app-network:
        driver: bridge

volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local