#  Dockerfile for Node Express Backend
# No bash, can still use once confident
# FROM node:alpine

FROM node:14
RUN npm install -g nodemon

RUN mkdir -p /app/server
WORKDIR /app/server


COPY package*.json /app/server/

RUN npm install --silent

COPY . /app/server/

CMD ["nodemon", "server.js"]